[package]
name = "j_lib_rust"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["dylib"]

[dependencies]
regex = "1.11.1"

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.21.1", default-features = false }

